"use client"
import type { Metadata} from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import publicURL from "@/functions/imageURL";
import Header from "@/components/Header";
import printOut from "@/functions/printOut";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Dictionary",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  printOut(`Rendering Root Layout`);

  return (
    <html>
      <body className={inter.className} >
        <Header></Header>

        {children}

        <><Script src={publicURL(`/js/theme.js`)} /></>
      </body>
    </html>

  );
}
